import Head from 'next/head';

const DefaultHead = () => (
  <Head>
    <title>球場坐座</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
);

export default DefaultHead;
