import Head from 'next/head';

import {
  Box,
  Heading,
  FormControl,
  FormLabel,
  FormHelperText,
} from '@chakra-ui/react';
import TextField from 'components/ui/TextField';

const ProfilePage = () => {
  return (
    <>
      <Head>
        <title>球場坐座</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box display="flex" flexDir="column">
        <Box>
          <Heading as="h2" size="xl">
            你好，歡迎加入
          </Heading>
        </Box>
        <Box display="flex" flexDir="column">
          <FormControl>
            <FormLabel htmlFor="email">電子信箱</FormLabel>
            <TextField id="email" value="value" />
            <FormHelperText>{"We'll never share your email."}</FormHelperText>
          </FormControl>
        </Box>
      </Box>
    </>
  );
};

export default ProfilePage;
