import Head from 'next/head';
import { Box } from '@chakra-ui/react';

import useAuth from 'lib/hooks/userAuth';

const ProfilePage = () => {
  const { isLoggedIn } = useAuth('/profile/sign-in');

  return (
    <>
      <Head>
        <title>球場坐座</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isLoggedIn && (
        <Box display="flex" flexDir="column" px={[4, 16]} py={4}>
          LOGIN
        </Box>
      )}
    </>
  );
};

export default ProfilePage;
