import Head from 'next/head';
import { Box } from '@chakra-ui/react';

import useAuth from 'lib/hooks/userAuth';

const ProfilePage = () => {
  const { isReady } = useAuth('profile/sign-in');

  let content = null;

  if (isReady) {
    content = (
      <Box display="flex" flexDir="column" px={[4, 16]} py={4}>
        LOGINNNNN
      </Box>
    );
  }

  console.log('ProfilePage.isReady', isReady);

  return (
    <>
      <Head>
        <title>球場坐座</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {content}
    </>
  );
};

export default ProfilePage;
