import Head from 'next/head';

import SpaceSelector from 'components/browse/space-selector';

const Home = () => {
  return (
    <>
      <Head>
        <title>球場坐座</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SpaceSelector />
    </>
  );
};

export default Home;
