import Head from 'next/head';

import { Box } from '@chakra-ui/react';

const UploadPage = () => {
  return (
    <>
      <Head>
        <title>球場坐座</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box h={1500}>
        <h1>UploadPage</h1>
      </Box>
    </>
  );
};

export default UploadPage;
