name: Storybook Build and Deploy
on:
  push:
    branches:
      - storybook-build-action

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install and Build
        run: | # Install npm packages and build the Storybook files
          npm install
          npm run build-storybook
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4
        with:
          branch: gh-pages
          folder: storybook-static
